version: '3.8'

services:
  web-template-ui:
    build:
      context: ui
      args:
        CONFIGURATION: development
    image: mitchellbarry/web-template-ui:dev
    environment:
      - TZ=America/Chicago
    ports:
      - 8876:80

  web-template-api:
    build:
      context: api
      args:
        CONFIGURATION: Debug
    image: mitchellbarry/web-template-api:dev
    environment:
      - TZ=America/Chicago
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8877:80